#!/bin/bash
#
# Check if you Handle variables replacement works

command="$PATH"
commandtwo="echo $PATH"

# clean up
stop_shell
rm -f $tmp_file

# send commands
echo "$commandtwo" | /bin/sh > path_route 2> $ERROROUTPUTFILE &
echo "$command" | $SHELL > test 2> youroutput &

# wait a little bit
$SLEEP $SLEEPSECONDS

# Answer
echo -n "$SHELL: 1: " > respuesta
echo -n $(cat path_route) >> respuesta
echo ": not found" >> respuesta

# Check the result
diff -q youroutput respuesta
math=$?
if [ $math -eq 0 ]; then
    print_ok_b
else
    print_ko
fi

# clean up
stop_shell
rm -f $tmp_file
rm -f youroutput
rm -f respuesta
rm -f path_route
rm -f test
