#!/bin/bash
#
# simple test with ls to check if the shell can find ls in the PATH

command="ls -la ls -1 ls -l"
tmp_file="checker_tmp_file_$RANDOM"

# clean up
stop_shell
rm -f $tmp_file

# create a pseudo random file
touch $tmp_file
# send commands
echo "$command" | $SHELL > $OUTPUTFILE 2> your_output &
echo "$command" | /bin/sh > /dev/null 2> $ERROROUTPUTFILE &

# wait a little bit
$SLEEP $SLEEPSECONDS

# Compare output
diff -q $ERROROUTPUTFILE your_output
match=$?
if [ $match -eq 0 ]; then
    print_ok
else
    print_ko
fi

# clean up
stop_shell
rm -f $tmp_file
rm -f your_output
